print(True)
print("Frue")
print(0 == 1)
print(3.14 > 2.42)
print(-1 <= 3)
print(3 != 3)
print(5 != 3)
print(True or False)
print(True or True)
print(True and False)
print(False and False)
print(False or False)
print(1 > 2 or 5 >= 1)
print(1 > 2 and 3 > 1)
print(1 == 1 and 0 == 0)
print(0 == False)
print(0.0 == False)
print(0.1 == False)