services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.monolith
    container_name: product-all-in-one
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: products
      POSTGRES_PORT: 5432
      PORT: 5000
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
