services:
  nginx:
    ports:
      - "80:80"

  adminer:
    ports:
      - "8080:8080"

  pgadmin:
    ports:
      - "5050:80"

  postgres:
    ports:
      - "5432:5432"

  backend_1:
    volumes:
      - ./backend:/app

  worker:
    volumes:
      - ./worker:/app
